/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gifplus_pcvimg_MainActivity */

#ifndef _Included_com_gifplus_pcvimg_MainActivity
#define _Included_com_gifplus_pcvimg_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_gifplus_pcvimg_MainActivity_MODE_PRIVATE
#define com_gifplus_pcvimg_MainActivity_MODE_PRIVATE 0L
#undef com_gifplus_pcvimg_MainActivity_MODE_WORLD_READABLE
#define com_gifplus_pcvimg_MainActivity_MODE_WORLD_READABLE 1L
#undef com_gifplus_pcvimg_MainActivity_MODE_WORLD_WRITEABLE
#define com_gifplus_pcvimg_MainActivity_MODE_WORLD_WRITEABLE 2L
#undef com_gifplus_pcvimg_MainActivity_MODE_APPEND
#define com_gifplus_pcvimg_MainActivity_MODE_APPEND 32768L
#undef com_gifplus_pcvimg_MainActivity_MODE_MULTI_PROCESS
#define com_gifplus_pcvimg_MainActivity_MODE_MULTI_PROCESS 4L
#undef com_gifplus_pcvimg_MainActivity_BIND_AUTO_CREATE
#define com_gifplus_pcvimg_MainActivity_BIND_AUTO_CREATE 1L
#undef com_gifplus_pcvimg_MainActivity_BIND_DEBUG_UNBIND
#define com_gifplus_pcvimg_MainActivity_BIND_DEBUG_UNBIND 2L
#undef com_gifplus_pcvimg_MainActivity_BIND_NOT_FOREGROUND
#define com_gifplus_pcvimg_MainActivity_BIND_NOT_FOREGROUND 4L
#undef com_gifplus_pcvimg_MainActivity_CONTEXT_INCLUDE_CODE
#define com_gifplus_pcvimg_MainActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_gifplus_pcvimg_MainActivity_CONTEXT_IGNORE_SECURITY
#define com_gifplus_pcvimg_MainActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_gifplus_pcvimg_MainActivity_CONTEXT_RESTRICTED
#define com_gifplus_pcvimg_MainActivity_CONTEXT_RESTRICTED 4L
#undef com_gifplus_pcvimg_MainActivity_RESULT_CANCELED
#define com_gifplus_pcvimg_MainActivity_RESULT_CANCELED 0L
#undef com_gifplus_pcvimg_MainActivity_RESULT_OK
#define com_gifplus_pcvimg_MainActivity_RESULT_OK -1L
#undef com_gifplus_pcvimg_MainActivity_RESULT_FIRST_USER
#define com_gifplus_pcvimg_MainActivity_RESULT_FIRST_USER 1L
#undef com_gifplus_pcvimg_MainActivity_DEFAULT_KEYS_DISABLE
#define com_gifplus_pcvimg_MainActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_gifplus_pcvimg_MainActivity_DEFAULT_KEYS_DIALER
#define com_gifplus_pcvimg_MainActivity_DEFAULT_KEYS_DIALER 1L
#undef com_gifplus_pcvimg_MainActivity_DEFAULT_KEYS_SHORTCUT
#define com_gifplus_pcvimg_MainActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_gifplus_pcvimg_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_gifplus_pcvimg_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_gifplus_pcvimg_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_gifplus_pcvimg_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     com_gifplus_pcvimg_MainActivity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_hello
  (JNIEnv *, jobject);
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_IsGettingGif
  (JNIEnv *env, jobject  jj);
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_GetImgbyID(JNIEnv *env, jobject  jj,jint id,jlong matAddrGr);
JNIEXPORT void  JNICALL Java_com_gifplus_pcvimg_MainActivity_ReleaseImglist(JNIEnv *env, jobject  jj);
JNIEXPORT void  JNICALL Java_com_gifplus_pcvimg_MainActivity_ReleaseBigShowImglist(JNIEnv *env, jobject  jj);

JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_GetImgListSize
  (JNIEnv *env, jobject  jj);
JNIEXPORT   jint  JNICALL Java_com_gifplus_pcvimg_MainActivity_SetHandImgMat(JNIEnv *env, jobject  jj,jlong matAddrGr, jlong matAddrRgba);
JNIEXPORT void JNICALL Java_com_gifplus_pcvimg_MainActivity_ReSize
(JNIEnv *env, jobject jo,jint type,jfloat range);
JNIEXPORT void  JNICALL Java_com_gifplus_pcvimg_MainActivity_Resumelist(JNIEnv *env, jobject  jj);
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_PerfCapVideo(JNIEnv *env, jobject  jj,jlong matAddrGr);

JNIEXPORT void  JNICALL Java_com_gifplus_pcvimg_MainActivity_SetSaveType(JNIEnv *env, jobject  jj,jint type);
JNIEXPORT jint   JNICALL Java_com_gifplus_pcvimg_MainActivity_InitVideoFile(JNIEnv *env, jobject,jstring path);
JNIEXPORT void  JNICALL Java_com_gifplus_pcvimg_MainActivity_SetEvery(JNIEnv *env, jobject  jj,jint ff);
JNIEXPORT void  JNICALL Java_com_gifplus_pcvimg_MainActivity_SetDelay(JNIEnv *env, jobject  jj,jint ff);
JNIEXPORT   void  JNICALL Java_com_gifplus_pcvimg_MainActivity_SetSize(JNIEnv *env, jobject  jj,jint size);
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_ConfirmKouTu
  (JNIEnv *env, jobject jj,jint x,jint y,jint wid,jint hei,jlong matAddrGr, jlong matAddrRgba);
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_InSertKoutu
  (JNIEnv *env, jobject jj,jint x,jint y,jint wid,jint hei,jlong matAddrGr,jlong aa);
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_InputBigShowMat
(JNIEnv *env, jobject jj,jlong matAddrGrRgba,jlong matAddrGr, jint id);
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_InputBigShowByPath
  (JNIEnv *env, jobject,jstring js,jint id);
JNIEXPORT void  JNICALL Java_com_gifplus_pcvimg_MainActivity_SetBigShowId(JNIEnv *env, jobject  jj,jint ff);
JNIEXPORT void  JNICALL Java_com_gifplus_pcvimg_MainActivity_SetEveryBigShow(JNIEnv *env, jobject  jj,jint ff);

JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_InSertImg
  (JNIEnv *env, jobject,jstring js,jint x,jint y,jint mode);
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_InSertTxt
  (JNIEnv *env, jobject,jstring js,jint x,jint y,jint mode);
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_GetGif
  (JNIEnv *env, jobject j,jstring js);
JNIEXPORT void JNICALL Java_com_gifplus_pcvimg_MainActivity_Start
  (JNIEnv *, jobject,jstring js);
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_PerfLiveFunc(JNIEnv *env, jobject  jj,jint nfun,jfloat nScale,jlong matAddrGr, jlong matAddrRgba, jlong matAddrRgbaF);
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_PerfEditFunc(JNIEnv *env, jobject  jj,jint nfun,jint nPause,jlong matAddrGr);
JNIEXPORT void JNICALL Java_com_gifplus_pcvimg_MainActivity_onmousekoutu
  (JNIEnv *env, jobject jj,jint event, jint x, jint y);
JNIEXPORT void JNICALL Java_com_gifplus_pcvimg_MainActivity_InitKoutou
  (JNIEnv *env, jobject jj,jlong matAddrGr, jlong matAddrRgba);
JNIEXPORT void JNICALL Java_com_gifplus_pcvimg_MainActivity_Stop
  (JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_gifplus_pcvimg_MainActivity_Pause
  (JNIEnv *, jobject);
JNIEXPORT int JNICALL Java_com_gifplus_pcvimg_MainActivity_TouchScreen
  (JNIEnv *env, jobject jo,jint event, jint x, jint y);
JNIEXPORT void JNICALL Java_com_gifplus_pcvimg_MainActivity_Rotate
(JNIEnv *env, jobject jo,jint num);
JNIEXPORT void JNICALL Java_com_gifplus_pcvimg_MainActivity_SetOperMode
(JNIEnv *env, jobject jo,jint  mode);
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_GetBMPCnt
(JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_com_gifplus_pcvimg_MainActivity_GetBMP
(JNIEnv *env, jobject jo,jint num);
JNIEXPORT void JNICALL Java_com_gifplus_pcvimg_MainActivity_GetInfo
(JNIEnv *env, jobject jo,jint num,jint type)
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_GetDly
(JNIEnv *env, jobject jo,jint num);
JNIEXPORT void JNICALL Java_com_gifplus_pcvimg_MainActivity_SetMode
(JNIEnv *env, jobject jo,jint  mode);
JNIEXPORT void JNICALL Java_com_gifplus_pcvimg_MainActivity_SetImgBtnPath
(JNIEnv *env, jobject jo,jstring ss);
JNIEXPORT void JNICALL Java_com_gifplus_pcvimg_MainActivity_SetColor
(JNIEnv *env, jobject jo,jint  color);
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_GetImgListWidth
(JNIEnv *env, jobject jo);
JNIEXPORT jint JNICALL Java_com_gifplus_pcvimg_MainActivity_GetImgListHeight
(JNIEnv *env, jobject jo);
#ifdef __cplusplus
}
#endif
#endif
